import {
  GitBranch,
  GitFork,
  FileText,
  QrCode,
  Palette,
  Image,
  Tag,
  Hash,
  Asterisk,
  Gauge,
  Globe,
  Clock,
  Weight,
  Regex,
  Binary,
  RectangleEllipsis,
  FileDigit,
  FileSearch,
  FileCog,
  Braces,
  Radar,
  Pipette,
  BookImage,
  Tags,
  ArrowLeftRight,
} from "lucide-react";

export const data = {
  navMain: [
    {
      title: "Visual",
      url: "#",
      items: [
        {
          title: "Image Optimizer",
          url: "/image-optimizer",
          isActive: false,
          isHighlight: true,
          icon: Image,
          cover: "/assets/screenshots/image-optimizer_j0NShGOYel.png",
        },
        {
          title: "Color Converter",
          url: "/color-converter",
          isActive: false,
          isHighlight: false,
          icon: Palette,
          cover: "/assets/screenshots/color-converter_GDpoaAY4YM.png",
        },
        {
          title: "Color Palette Picker",
          url: "/color-palette-picker",
          isActive: false,
          isHighlight: false,
          icon: Pipette,
          cover: "/assets/screenshots/color-palette-picker_8ljNF9Db1c.png",
        },
      ],
    },
    {
      title: "Security",
      url: "#",
      items: [
        // {
        //   title: "URL + IP Checker",
        //   url: "/urlscanner",
        // },
        {
          title: "Password Generator",
          url: "/passgen",
          icon: RectangleEllipsis,
          isHighlight: false,
          cover: "/assets/screenshots/passgen_tXM7Eg4Y7f.png",
        },
        {
          title: "Password Checker",
          url: "/passcheck",
          icon: Radar,
          isHighlight: true,
          cover: "/assets/screenshots/passcheck_HCtKHmwDV6.png",
        },
        {
          title: "JWT Decoder",
          url: "/jwtdecoder",
          icon: Binary,
          isHighlight: false,
          cover: "/assets/screenshots/jwtdecoder_CZrrgQAGAm.png",
        },
      ],
    },
    {
      title: "Web & Dev",
      url: "#",
      items: [
        {
          title: "Meta Tag Preview",
          url: "/meta-tag-preview",
          icon: Tag,
          isHighlight: false,
          cover: "/assets/screenshots/seo-metatag-generator_0f7bmKEuzX.png",
        },
        {
          title: "PageSpeed Insights",
          url: "/pagespeed",
          icon: Gauge,
          isHighlight: true,
          cover: "/assets/screenshots/pagespeed_c5YE7Zl7cE.png",
        },
        {
          title: "Domain Lookup",
          url: "/domainlookup",
          icon: Globe,
          isHighlight: false,
          cover: "/assets/screenshots/domainlookup_WWShZtTgso.png",
        },
        {
          title: "Favicon Generator",
          url: "/favicon-generator",
          icon: BookImage,
          isHighlight: false,
          cover: "/assets/screenshots/favicon-generator_IJ6LIqHj84.png",
        },
        {
          title: "SEO Meta Tag Generator",
          url: "/seo-metatag-generator",
          icon: Tags,
          isHighlight: true,
          cover: "/assets/screenshots/seo-metatag-generator_0f7bmKEuzX.png",
        },
      ],
    },
    {
      title: "Health",
      url: "#",
      items: [
        {
          title: "BMI Calculator",
          url: "/bmi-calculator",
          icon: Weight,
          isHighlight: true,
          cover: "/assets/screenshots/bmi-calculator_YEb6zMeGNJ.png",
        },
      ],
    },
    {
      title: "Utilities",
      url: "#",
      items: [
        // {
        //   title: "WHOIS + DNS Lookup",
        //   url: "/whois",
        // },
        {
          title: "Timestamp Converter",
          url: "/timestamp",
          icon: Clock,
          isHighlight: false,
          cover: "/assets/screenshots/timestamp_vUDVAxGfur.png",
        },
        {
          title: "File Checksum Generator",
          url: "/filechecksum",
          icon: FileDigit,
          isHighlight: false,
          cover: "/assets/screenshots/filechecksum_XV57JQ5yzj.png",
        },
        {
          title: "JSON ↔ CSV Converter",
          url: "/jsoncsv",
          icon: FileCog,
          isHighlight: false,
          cover: "/assets/screenshots/jsoncsv_7aF9McYK72.png",
        },
        {
          title: "QR Code Generator",
          url: "/qrcode",
          icon: QrCode,
          isHighlight: false,
          cover: "/assets/screenshots/qrcode_UCDQrIXi96.png",
        },
        {
          title: "Base64 Studio",
          url: "/base64",
          icon: Braces,
          isHighlight: false,
          cover: "/assets/screenshots/base64_cUSalTcz5n.png",
        },
        {
          title: "Hash Generator",
          url: "/hashgen",
          icon: Hash,
          isHighlight: false,
          cover: "/assets/screenshots/hashgen_tqdCyaDsj5.png",
        },
        {
          title: "UUID Generator",
          url: "/uuidgen",
          icon: Asterisk,
          isHighlight: false,
          cover: "/assets/screenshots/uuidgen_GAZj4QUoeG.png",
        },
        {
          title: "Regex Tester",
          url: "/regex-tester",
          icon: Regex,
          isHighlight: false,
          cover: "/assets/screenshots/regex-tester_E3PR2ut1IG.png",
        },
        {
          title: "Markdown Preview",
          url: "/markdown-preview",
          icon: FileSearch,
          isHighlight: false,
          cover: "/assets/screenshots/markdown-preview_WXseOgX5XH.png",
        },
        {
          title: "Unit Converters",
          url: "/unit-converters",
          icon: ArrowLeftRight,
          isHighlight: false,
          cover: "/assets/screenshots/unit-converters_0ABbZ7EDEr.png",
        },
      ],
    },
  ],
  navSecondary: [
    {
      title: "Source Code",
      url: "https://github.com/KawanuaDev/app-kawanua",
      icon: GitBranch,
      isHighlight: false,
    },
    {
      title: "Berkontribusi",
      url: "https://github.com/KawanuaDev/app-kawanua/blob/main/CONTRIBUTING.md",
      icon: GitFork,
      isHighlight: false,
    },
    {
      title: "License",
      url: "https://github.com/KawanuaDev/app-kawanua/blob/main/LICENSE",
      icon: FileText,
      isHighlight: false,
    },
  ],
};
